version: '3.8'

services:
  backend:
    image: wireguard-backend:latest
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - DB_PATH=/app/data/wireguard_manager.db
      - LOG_LEVEL=INFO
    volumes:
      - wireguard-db:/app/data
      - wireguard-logs:/app/logs
    networks:
      - wireguard-network
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
      rollback_config:
        parallelism: 1
        delay: 10s
      placement:
        constraints:
          - node.role == worker
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    image: wireguard-frontend:latest
    build: .
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    volumes:
      - wireguard-nginx-logs:/var/log/nginx
    networks:
      - wireguard-network
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
      rollback_config:
        parallelism: 1
        delay: 10s
      placement:
        constraints:
          - node.role == worker
      resources:
        limits:
          memory: 256M
          cpus: '0.25'
        reservations:
          memory: 128M
          cpus: '0.1'

networks:
  wireguard-network:
    driver: overlay
    attachable: true
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  wireguard-db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/wireguard/data
  wireguard-logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/wireguard/logs
  wireguard-nginx-logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/wireguard/logs/nginx