version: '3.8'

services:
  backend:
    image: dg95/wiredash-backend:1.0.0
    environment:
      - FLASK_ENV=production
      - DB_PATH=/app/data/wireguard_manager.db
      - LOG_LEVEL=INFO
    volumes:
      - wiredash-db:/app/data
      - wiredash-logs:/app/logs
    networks:
      - traefik_public
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  wiredash:
    image: dg95/wiredash-front:1.0.0
    networks:
      - traefik_public
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
      placement:
        constraints:
          - node.role == worker
      resources:
        limits:
          memory: 512M
          cpus: '0.5'

networks:
  traefik_public:
    external: true

volumes:
  wiredash-db:
    external: true
  wiredash-logs:
    external: true